language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: HAvgXGQV7rB7fqwrx8lHSXT9eP3UCRYL7wgqRCWiQfskwLax6JpuNt3SmsAN7fl1MHMCWzj6KZLQLJAUXVtqIs1uMnpbCp83kL2c3ZxXRtFyqZPlTUe9V0hOUUtYNkVEyWAz2Cb68nbU50UFzROLxe+7RHreHuctzxmsKyR40IeQ6xY//ArlaCye8Ss2Fgu84C1QGbV00m6juB7Xe2bu7bZJJNW0U67ESRBTVyN96OMLS9wUxohIXvY+B35zvIFiyg6+rGa4yaqRGZVeOdbSjJnItdOs9KKgdJfF7LzL3nlJXVirdgSK1gEG8niBK0Eb75EW6t/YRZRnrw6UXozRirH2Wdz7GQW6ZVVDMsqRTIGyPVgvMaFJgUJNQCJTtuXxuyoWySRpZ2UnNAaUtIBtLc/BZjFFY2p8XVvytmhJIsqHGVghc2mm78m2OHmlH/CEA2V8RJnvO8eFE0lh5VSE9Kl0s8DOgYTrlO2ONnSStUA1FpH5gLx9ZU6PmHVMzpiDvgSB53o2mfSHmXlm1u1Fa/sWEcoqD3I0SFxBCTJaqkxQYJFLNuQLuPO9x8GrXb39/BVbuzwACAVuDYRtLli3o7XTx3Rhg6gSwXiQRfc6rtdcKBgWnyYLnMzJCm7T3dH6W9Xnx02gMhk21roLBdHNQLC6niBzAzO/okF6/Hbp2ek=
  app: sheltered-bayou-52199
  on:
    repo: rjwilliams87/hot-cold-challenge
